version: "2.0"
services:
  postgres:
    container_name: postgres_mk
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: main_table
    ports:
      - "5432:5432"
    restart: unless-stopped
